server:
  port: 8080

spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:/schema.sql
      data-locations: classpath:/data.sql
  r2dbc:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1

  h2:
    console:
      enabled: true
      port: 8090