CREATE TABLE IF NOT EXISTS category (
    category VARCHAR(255) NOT NULL,
    PRIMARY KEY (category)
);

CREATE TABLE IF NOT EXISTS goods
(
    id bigint NOT NULL AUTO_INCREMENT,
    brand VARCHAR(255),
    price DECIMAL(10),
    category VARCHAR(255),
    ins_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ins_oprt VARCHAR(255),
    upd_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
    upd_oprt VARCHAR(255),
    PRIMARY KEY (id),

    CONSTRAINT FK_GOODS_CATEGORY FOREIGN KEY (category) REFERENCES category(category)
);